<?php

const USUARIO = "USUARIO";
const USU_ID = "USU_ID";
const USU_NOMBRE = "USU_NOMBRE";
const USU_EMAIL = "USU_EMAIL";
const USU_TELEFONO = "USU_TELEFONO";
const USU_DIRECCION = "USU_DIRECCION";
const USU_ESTATUS = "USU_ESTATUS";
const USU_PASSWORD = "USU_PASSWORD";
